#!/usr/bin/env bash
#
# Builds the Debian and RPM packages for the host architecture.
#
#   ./packaging/linux/build-packages.sh
#
# Everything about the package contents — files, permissions, dependencies,
# descriptions — lives in [package.metadata.deb] and
# [package.metadata.generate-rpm] in Cargo.toml. This script only sequences the
# steps, because both packagers expect the release binary and the completion
# scripts to already exist.
#
# Requires: cargo install cargo-deb cargo-generate-rpm

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$repo_root"

# Read the version from the one place it is defined. `^version` only matches
# the [package] key; dependency versions are nested inside inline tables.
version="$(sed -n 's/^version *= *"\([^"]*\)".*/\1/p' Cargo.toml | head -n 1)"
dist="$repo_root/dist"

echo "==> Building rust-example $version"
cargo build --release --locked

# The completion scripts are generated by the binary that was just built, so
# they can never describe a different set of flags than it accepts.
echo "==> Generating shell completions"
completions="$repo_root/target/completions"
rm -rf "$completions"
for shell in bash zsh fish; do
    ./target/release/rust-example completions "$shell" --out-dir "$completions"
done

# --no-build: reuse the binary above rather than building it a second time
# without the release profile settings from Cargo.toml.
echo "==> Building .deb"
cargo deb --no-build --no-strip

echo "==> Building .rpm"
cargo generate-rpm

mkdir -p "$dist"
find target/debian target/generate-rpm -maxdepth 1 -type f \( -name '*.deb' -o -name '*.rpm' \) \
    -exec cp {} "$dist/" \;

echo "==> Packages in $dist"
ls -1 "$dist"

# Worth doing in CI as well as locally: a package that installs but does not
# run is a package that shipped broken.
if command -v dpkg-deb >/dev/null 2>&1; then
    echo "==> Contents of the .deb"
    dpkg-deb --contents "$dist"/*.deb
fi
